version: '3.4'

services:
  amasingame-api:
    image: amasingame-api
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      - PORT=8000
  amasingame-web:
    image: amasingame-web
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
  db:
    image: postgres:13.4
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: amasin
    volumes:
      - ./backend/docker/postgres:/docker-entrypoint-initdb.d
